### ISSUE TITLE
Manual Install steps fail due to incorrectly named cg_custom_core

### ISSUE THREAD

**Issue by Arron17** [chrisgoringe/cg-noise#10]
In the manual install steps it advises to run the command

`git clone https://github.com/chrisgoringe/cg-custom-core.git`

This creates a folder called "cg-custom-core" with hypens.

However the hijack.py script calls "cg_custom_core" with underscores. The Install.py script changes the folder name to "cg_custom_core" with underscores.

The installation steps need to either cover changing the folder name, or the script should call cg-custom-core instead so it fits with the github naming convention.

**Comment by chrisgoringe** [comment]
Thanks for picking this up - the manual install steps have been corrected to 

`git clone https://github.com/chrisgoringe/cg-custom-core.git cg_custom_core`

and the update steps similarly.
